### PR TITLE
Feature fix render new event type dashboard

### LINKED ISSUE #18: IN: Dashboard
Integrate user's meetings controller

### LINKED ISSUE #58: Bug: UserContext Provider not loading fast enough to allow components to render with data provided to them in Dashboard (Event Types)
I'm getting stuck on getting the data from UserProvider.context to display user data on the dashboard because it's giving me a similar undefined error I got on the New Events page. The difference here is that the page expects to load the data right away as opposed to having to click a button to retrieve the data as in the New Events page.

Error Message:
```js
TypeError: userData.user is undefined
EventTypes
src/pages/dashboard/EventTypes.js:53

  50 | </Grid>
  51 | <Grid container direction="column" item xs={11}>
  52 |   <Grid item>
> 53 |     <Typography>{userData.user.firstName} {userData.user.lastName}</Typography>
     | ^  54 |   </Grid>
  55 |   <Grid item>
  56 |     <Typography color="primary">calendly.com/{userData.user.firstName.toLowerCase()}-{userData.user.lastName.toLowerCase()}</Typography>
```
Is there a react method that waits for context data to load before rendering the components from using it? I tried using a ternary operation below to check if undefined:
```js 
<Typography>{typeof userData === undefined ? "Loading" : userData.user.firstName} {typeof userData === undefined ? "Loading" : userData.user.lastName}</Typography>
```
but that isn't making the error go away. I tried looking on stack overflow, but not finding anything that can help at the moment.

### LINKED ISSUE #61: Fix/Optimization: Adding New Event Type to Dashboard
### Expected Behavior
* after hitting submit to create a New Event Type, it should show up on the user's dashboard right away

### Actual Behavior
* after hitting submit to create a New Event Type, you need to manually refresh the page to see the event type added to the dashboard

### PR DESCRIPTION
**Pull request by singhmi4**
### What it Does
* when creating a new Event Type (Meeting Type) through an axios post request, addMeetingType function is called from UserProvider context and the new Event Type is passed in which updates the user state before redirecting to the Dashboard:
```js
const addMeetingTypes = (newMeetingType) => {
      setUser(prevUser => { 
        return {
          user: {
          // copies the previous user object
          ...prevUser.user, 
          // appends the newMeetingType created to the meetingTypes object
          meetingTypes: [...prevUser.user.meetingTypes, newMeetingType] 
        } 
      }});
    }
```
### What to Look For
* DRY code
* code review from #59 will be addressed here

### What to Avoid
* #59 will not be merged in as this one includes all of the commits from that branch
* context performing the actions that would make more sense in a reducer

### CODE REVIEW

**Review by bonnieli — APPROVED** [review]

**Comment by bonnieli** [comment]
I think this would also close https://github.com/hatchways/team-vampire/pull/60 right?

File: client/src/pages/dashboard/EventTypes.js [hunk 1]
```diff
@@ -32,54 +33,57 @@ const EventTypes = () => {
   const classes = useStyles();
   const theme = useTheme();
   const matches = useMediaQuery(theme.breakpoints.up("md"));
+
+  const userData = useContext(UserProvider.context);
+
```
Comment (bonnieli) [inline client/src/pages/dashboard/EventTypes.js:39]:
```
const currentUser = userData.user.user;
```

that way we can call just 

```
{currentUser && (
...
```

**Review by bonnieli — APPROVED** [review]

File: client/src/pages/dashboard/EventTypes.js (hunk 1 above)
Comment (singhmi4) [reply client/src/pages/dashboard/EventTypes.js:39]: change to be addressed in branch associated to #66
